INFO:root:10/29/2019, 21:27:16 : rule match does not exist, create new rule for sample_gpa.csv
INFO:root:10/29/2019, 21:53:04 : rule match does not exist, create new rule for sample_gpa.csv
INFO:root:10/30/2019, 16:09:17 : rule submission successful for sample_stocks.txt
INFO:root:10/30/2019, 16:25:47 : rule submission successful for sample_stocks.txt
INFO:root:10/30/2019, 16:27:04 : rule match does not exist, create new rule for sample_gpa.csv
INFO:root:10/30/2019, 16:27:04 : sample_stocks.txt successfully uploaded to database
INFO:root:10/30/2019, 16:44:37 : rule match does not exist, create new rule for sample_gpa.csv
INFO:root:10/30/2019, 16:44:37 : rule match does not exist, create new rule for sample_stocks.txt
INFO:root:10/30/2019, 17:41:37 : rule submission successful for sample_stocks.txt
INFO:root:10/30/2019, 17:42:34 : rule match does not exist, create new rule for sample_gpa.csv
INFO:root:10/30/2019, 17:42:34 : sample_stocks.txt successfully uploaded to database
INFO:root:11/19/2019, 11:53:26 : rule submission successful for f1.txt
INFO:root:11/19/2019, 11:53:26 : rule match does not exist, create new rule for f1.txt
INFO:root:11/19/2019, 11:55:22 : rule submission successful for f1.txt
INFO:root:11/19/2019, 11:58:39 : rule submission successful for f1.txt
INFO:root:11/19/2019, 13:26:49 : rule submission successful for f1.txt
INFO:root:11/19/2019, 13:29:16 : rule already exists in database for f1.txt
INFO:root:11/19/2019, 13:43:18 : f1.txt successfully uploaded to database
INFO:root:11/19/2019, 19:03:48 : rule submission successful for f1.txt
INFO:root:11/19/2019, 19:23:02 : rule submission successful for f1.txt
INFO:root:11/19/2019, 19:23:02 : f1.txt successfully uploaded to database
INFO:root:11/19/2019, 19:36:27 : rule already exists in database for f1.txt
INFO:root:11/19/2019, 19:38:54 : rule already exists in database for f1.txt
INFO:root:11/19/2019, 19:54:42 : rule submission successful for sample_web_file.csv
INFO:root:11/19/2019, 19:57:25 : rule already exists in database for sample_web_file.csv
INFO:root:11/19/2019, 19:57:41 : rule already exists in database for sample_web_file.csv
INFO:root:11/19/2019, 19:57:43 : rule match does not exist, create new rule for sample_web_file.csv
INFO:root:11/19/2019, 19:59:51 : rule match does not exist, create new rule for sample_web_file.csv
INFO:root:11/19/2019, 20:03:07 : rule match does not exist, create new rule for sample_web_file.csv
INFO:root:11/19/2019, 20:04:01 : rule match does not exist, create new rule for sample_web_file.csv
INFO:root:11/19/2019, 20:16:18 : sample_web_file.csv successfully uploaded to database
INFO:root:11/27/2019, 18:47:50 : rule submission successful for mass_dataset.csv
ERROR:django.request:Internal Server Error: /submit_rule/
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\RepoScanner.py changed, reloading.
INFO:root:11/27/2019, 19:05:00 : rule submission successful for mass_dataset.csv
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\views.py changed, reloading.
INFO:root:11/27/2019, 19:09:25 : rule submission successful for mass_dataset.csv
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\RepoScanner.py changed, reloading.
WARNING:django.request:Bad Request: /sync/
WARNING:django.request:Bad Request: /sync/
WARNING:django.request:Bad Request: /sync/
WARNING:django.request:Bad Request: /sync/
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\views.py changed, reloading.
INFO:root:11/27/2019, 19:35:24 : rule match does not exist, create new rule for mass_dataset.csv
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\RepoScanner.py changed, reloading.
INFO:root:11/27/2019, 19:41:11 : rule submission successful for mass_dataset.csv
INFO:root:11/28/2019, 09:35:44 : rule already exists in database for mass_dataset.csv
INFO:root:11/28/2019, 09:36:36 : rule already exists in database for mass_dataset.csv
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\Admin.py changed, reloading.
INFO:root:11/28/2019, 10:59:35 : rule match does not exist, create new rule for mass_dataset.csv
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\Admin.py changed, reloading.
INFO:root:11/28/2019, 11:07:15 : rule submission successful for mass_dataset.csv
INFO:root:11/28/2019, 11:10:54 : rule submission successful for mass_dataset.csv
INFO:root:11/28/2019, 11:48:41 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:18:07 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:19:04 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:20:01 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:20:59 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:22:01 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:24:26 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 12:25:23 : mass_dataset.csv successfully uploaded to database
INFO:root:11/28/2019, 13:18:26 : mass_dataset.csv successfully uploaded to database
INFO:django.utils.autoreload:C:\code\project_flex\ETL-2019\Team4\ETLFlex\rules\FlexFile\Database\Database.py changed, reloading.
